web/config/routes.rb
Project::Application.routes.draw do
  
  namespace :admin do
     root :to => "admins#index"
     resources :clips
     resources :packages
     resources :raw_videos
     resources :admin_tasks
     resources :transcoding_tasks, :controller => "admin_tasks"
     resources :package_tasks, :controller => "admin_tasks"
  end

  match 'admin/clips/:id/stream' => 'admin/clips#stream', :as => :stream_clip
       
  devise_for :admins , :path => "admin"

  get "/test" => "test#index"

  root :to => "Admin#edit"

end

web/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

web/app/models/admin_task.rb
class AdminTask < ActiveRecord::Base

end

class TranscodingTask < AdminTask
    belongs_to :raw_video
    
end

class PackageTask < AdminTask
end

web/app/models/caption.rb
class Captions < ActiveRecord::Base
    belongs_to :package
end

web/app/models/captions.rb
class Captions < ActiveRecord::Base
    belongs_to :package
end

web/app/models/clip.rb
class Clip < ActiveRecord::Base
end

web/app/models/package.rb
class Package < ActiveRecord::Base
    has_many :raw_videos
    has_many :captions
    
end

web/app/models/program.rb
class Program < ActiveRecord::Base
    has_many :video_resources
end

web/app/models/raw_video.rb
class RawVideo < ActiveRecord::Base
    has_many :raw_video_streams
    has_many :clips
    has_many :transcoding_tasks
    belongs_to :package
    
end

web/app/models/raw_video_stream.rb
class RawVideoStream < ActiveRecord::Base
    belongs_to :RawVideo
end

web/app/models/video_resource.rb
class VideoResource < ActiveRecord::Base
      belongs_to :program
end

web/app/controllers/admin/admins_controller.rb
require "admin_task.rb"

class Admin::AdminsController < ApplicationController
    #before_filter :authenticate_admin!
    
    def index
        #ongoing package task
        
        @package_ing = PackageTask.where(:status => 'ing')
        @package_tasks = PackageTask.where(:status => 'new')
        @package_failed_tasks = PackageTask.where(:status => 'failed')   
        @packages = Package.all
        
        #ongoing transcoding task
        @transcoding_ing = TranscodingTask.where(:status => 'ing')
        @transcoding_tasks = TranscodingTask.where(:status => 'new')
    end
    
    def create
        
    end
end

web/app/controllers/admin/clips_controller.rb
class Admin::ClipsController < ApplicationController
    def show
        @clip = Clip.find(params[:id])
    end
    
    def stream
        @clip = Clip.find(params[:id])
        
        if !@clip.nil?
            send_file @clip.location, :type => "video/x-f4v"
            return
        else
            render :text => "404 Not Found", :status => 404
        end
    end
end

web/app/controllers/admin/raw_videos_controller.rb
class Admin::RawVideosController < ApplicationController
  # GET /raw_videos
  # GET /raw_videos.xml
  def index
    @raw_videos = RawVideo.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @raw_videos }
    end
  end

  # GET /raw_videos/1
  # GET /raw_videos/1.xml
  def show
    @video = RawVideo.find(params[:id])
    @transcoding_new = TranscodingTask.where(:raw_video_id => params[:id], :status => "new")
    @transcoding_failed = TranscodingTask.where(:raw_video_id => params[:id], :status => "failed")
    @transcoding_ing = TranscodingTask.where(:raw_video_id => params[:id], :status => "ing")

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @raw_video }
    end
  end

  # GET /raw_videos/new
  # GET /raw_videos/new.xml
  def new
    @raw_video = RawVideo.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @raw_video }
    end
  end

  # GET /raw_videos/1/edit
  def edit
    @raw_video = RawVideo.find(params[:id])
  end

  # POST /raw_videos
  # POST /raw_videos.xml
  def create
    @raw_video = RawVideo.new(params[:raw_video])

    respond_to do |format|
      if @raw_video.save
        format.html { redirect_to(@raw_video, :notice => 'Raw video was successfully created.') }
        format.xml  { render :xml => @raw_video, :status => :created, :location => @raw_video }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @raw_video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /raw_videos/1
  # PUT /raw_videos/1.xml
  def update
    @raw_video = RawVideo.find(params[:id])

    respond_to do |format|
      if @raw_video.update_attributes(params[:raw_video])
        format.html { redirect_to(@raw_video, :notice => 'Raw video was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @raw_video.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /raw_videos/1
  # DELETE /raw_videos/1.xml
  def destroy
    @raw_video = RawVideo.find(params[:id])
    @raw_video.destroy

    respond_to do |format|
      format.html { redirect_to(raw_videos_url) }
      format.xml  { head :ok }
    end
  end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

web/app/helpers/admin_helper.rb
module AdminHelper
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/common.rb
../../../scripts/common.rb

web/app/helpers/packages_helper.rb
module PackagesHelper
end

web/app/helpers/raw_videos_helper.rb
module RawVideosHelper
end

web/app/helpers/tasks_helper.rb
module TasksHelper
end

web/app/helpers/video.rb
../../../scripts/video.rb

web/app/helpers/video_resource_helper.rb
module VideoResourceHelper
end

web/app/helpers/video_resources_helper.rb
module VideoResourcesHelper
end

web/app/views/admin/raw_videos/_form.html.erb
<%= form_for(@raw_video) do |f| %>
  <% if @raw_video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@raw_video.errors.count, "error") %> prohibited this raw_video from being saved:</h2>

      <ul>
      <% @raw_video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

web/app/views/admin/raw_videos/edit.html.erb
<h1>Editing raw_video</h1>

<%= render 'form' %>

<%= link_to 'Show', @raw_video %> |
<%= link_to 'Back', raw_videos_path %>

web/app/views/admin/raw_videos/index.html.erb
<h1>Listing raw_videos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @raw_videos.each do |raw_video| %>
  <tr>
    <td><%= raw_video.location %></td>
    <td><%= link_to 'Show', raw_video %></td>
    <td><%= link_to 'Edit', edit_raw_video_path(raw_video) %></td>
    <td><%= link_to 'Destroy', raw_video, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

web/app/views/admin/raw_videos/new.html.erb
<h1>New raw_video</h1>

<%= render 'form' %>

<%= link_to 'Back', raw_videos_path %>

web/app/views/admin/raw_videos/show.html.erb
<p id="notice"><%= notice %></p>

<table>
<tr><td>Title</td>      <td><%= @video.title %> </td></tr>
<tr><td>Location</td>   <td><%= @video.location %></tr>
<tr><td>Bitrate(kbps)</td><td><%= @video.bitrate.to_i/1024 %></tr>
<tr><td>Format</td>  <td><%= @video.format %></td></tr>
<tr><td>Duration(mins)</td> <td><%= @video.duration/60 %> </td></tr>
<tr><td>Size(M)</td>      <td><%= @video.size.to_i/1024/1024 %></td>
<tr><td>Author</td>      <td><%= @video.author %></td>
<tr><td>Copyright</td>      <td><%= @video.copyright %></td>
<tr><td>Comment</td>      <td><%= @video.comment %></td>
</table>

<h4>Streams</h4>
<table>
<tr>
<td>Index</td>
<td>Codec</td>
<td>Codec Long</td>
<td>Type</td>
<td>Sample Rate</td>
<td>Channels</td>
<td>Bits Per Sample</td>
<td>Average Framerate</td>
<td>Start Time</td>
<td>Duration</td>
</tr>
<% @video.raw_video_streams.each do |stream| %>
<tr>
<td><%= stream.index%></td>
<td><%= stream.codec%></td>
<td><%= stream.codec_long%></td>
<td><%= stream.type%></td>
<td><%= stream.sample_rate%></td>
<td><%= stream.channels%></td>
<td><%= stream.bits_per_sample%></td>
<td><%= stream.avg_framerate%></td>
<td><%= stream.start_time%></td>
<td><%= stream.duration%></td>
</tr>
<% end %>
</table>

<h4>Clips</h4>
<table>
<tr>
<td>Location </td>
<td>Bitrate</td>
<td>Start Time</td>
<td>Duration</td>
<td>Operation</td>
</tr>
<% @video.clips.each do |clip| %>
<tr>
<td><%= clip.location%></td>
<td><%= clip.bitrate%></td>
<td> 0 </td>
<td><%= clip.duration%></td>
<td> <%= link_to "Play", admin_clip_path(clip) %> </td>
</tr>
<% end %>
</table>

<h4>Transcoding</h4>
<table>
<tr>
<td>Location </td>
<td>Bitrate</td>
<td>Start Time</td>
<td>Duration</td>
<td>Status</td>
</tr>
<% @transcoding_ing.each do |clip| %>
<tr>
<td><%= clip.location%></td>
<td><%= clip.bitrate%></td>
<td> 0 </td>
<td> 0 </td>
<td style="color:green">Transcoding</td>
</tr>
<% end %>
<% @transcoding_new.each do |clip| %>
<tr>
<td><%= clip.location%></td>
<td><%= clip.bitrate%></td>
<td> 0 </td>
<td> 0 </td>
<td>Queue</td>
</tr>
<% end %>
</table>

<% if @transcoding_failed.size != 0 %>
<h4>Failed</h4>
<table>
<tr>
<td>Location </td>
<td>Bitrate</td>
<td>Start Time</td>
<td>Duration</td>
<td>Error</td>
</tr>
<% @transcoding_failed.each do |clip| %>
<tr>
<td><%= clip.location%></td>
<td><%= clip.bitrate%></td>
<td> 0 </td>
<td> 0 </td>
<td style="color:red"><%= clip.err_msg %></td>
</tr>
<% end %>
</table>
<% end %>


<br>
<%= link_to 'Transcode', new_admin_admin_task_path(:type => "transcoding", :raw_video_id => @video.id) %> |
<%= link_to 'Back', admin_package_path(@video.package) %>