web/config/routes.rb
Project::Application.routes.draw do
  
  namespace :admin do
     root :to => "admins#index"
     resources :clips
     resources :packages
     resources :raw_videos
     resources :admin_tasks
     resources :transcoding_tasks, :controller => "admin_tasks"
     resources :package_tasks, :controller => "admin_tasks"
  end

  match 'admin/clips/:id/stream' => 'admin/clips#stream', :as => :stream_clip
       
  devise_for :admins , :path => "admin"

  get "/test" => "test#index"

  root :to => "Admin#edit"

end

web/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

web/app/models/admin_task.rb
class AdminTask < ActiveRecord::Base

end

class TranscodingTask < AdminTask
    belongs_to :raw_video
    
end

class PackageTask < AdminTask
end

web/app/models/caption.rb
class Captions < ActiveRecord::Base
    belongs_to :package
end

web/app/models/captions.rb
class Captions < ActiveRecord::Base
    belongs_to :package
end

web/app/models/clip.rb
class Clip < ActiveRecord::Base
end

web/app/models/package.rb
class Package < ActiveRecord::Base
    has_many :raw_videos
    has_many :captions
    
end

web/app/models/program.rb
class Program < ActiveRecord::Base
    has_many :video_resources
end

web/app/models/raw_video.rb
class RawVideo < ActiveRecord::Base
    has_many :raw_video_streams
    has_many :clips
    has_many :transcoding_tasks
    belongs_to :package
    
end

web/app/models/raw_video_stream.rb
class RawVideoStream < ActiveRecord::Base
    belongs_to :RawVideo
end

web/app/models/video_resource.rb
class VideoResource < ActiveRecord::Base
      belongs_to :program
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

web/app/helpers/admin_helper.rb
module AdminHelper
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/helpers/common.rb
../../../scripts/common.rb

web/app/helpers/packages_helper.rb
module PackagesHelper
end

web/app/helpers/raw_videos_helper.rb
module RawVideosHelper
end

web/app/helpers/tasks_helper.rb
module TasksHelper
end

web/app/helpers/video.rb
../../../scripts/video.rb

web/app/helpers/video_resource_helper.rb
module VideoResourceHelper
end

web/app/helpers/video_resources_helper.rb
module VideoResourcesHelper
end

web/app/views/admin/admins/index.html.erb
<% if admin_signed_in? %>
Signed in as <%= current_admin.email %>.
<%= link_to 'Sign out', destroy_admin_session_path %>
<% end %>


<h2>Admin portal</h2>

<h3>Package</h3>
<%= link_to "New package", new_admin_admin_task_path(:type => "package") %><br><br>

<% if @package_ing.size != 0 or @package_tasks.size != 0 %>
<h4>processing packages</h4>
<% end %>

<% if @package_ing.size != 0 %>

   <% @package_ing.each do |p| %>
   -> <%= p.location %>
   <% end %>
<br>
<%end%>

<% if @package_tasks.size != 0 %>
    <table>
    <tr>
    <td>ID</td>
    <td>Location</td>
    <td>Status</td>
    <td>Operatorn</td>
    </tr>
    <% @package_tasks.each do |task| %>
        <tr>
        <td><%= task.id %></td>
        <td><%= task.location %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Destroy', [:admin,task], :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
    <% end %>
    </table>
<% end %>

<% if @package_failed_tasks.size != 0 %>
<h4 style="color:red">Failed packages</h4>
    <table>
    <tr>
    <td>ID</td>
    <td>Location</td>
    <td>Error msg</td>
    <td>Operatorn</td>
    </tr>
    <% @package_failed_tasks.each do |task| %>
        <tr>
        <td><%= task.id %></td>
        <td><%= task.location %></td>
        <td><%= task.err_msg %></td>
        <td><%= link_to 'Destroy', [:admin,task], :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
    <% end %>
    </table>
<% end %>

<% if @packages.size != 0 %>
<h4 style="color:green">packages</h4>
    <table>
    <tr>
    <td>ID</td>
    <td>Location</td>
    <td>Videos</td>
    <td>Captions</td>
    <td>Operatorn</td>

    </tr>
    <% @packages.each do |package| %>
        <tr>
        <td><%= package.id %></td>
        <td><%= link_to package.location, [:admin, package] %></td>
        <td><% if package.raw_videos.nil? %> 0 <% else %> <%= package.raw_videos.size %> <% end %>
        <td> 0
        <td><%= link_to 'Destroy', [:admin,package], :confirm => 'Are you sure?', :method => :delete %></td>
        </tr>
    <% end %>
    </table>
<% end %>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
  <style type="text/css">
    table{
        border-collapse: collapse;
    }
    td { 
        border-width : 1px;
        border-style: solid; 
        border-spacing: 0;
        border-color: gray;
        
        padding: 4px;
    }
  </style>
  
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>